/**
 * Hand-written domain types matching the Phase 1 schema
 * (supabase/migrations/*.sql). These are NOT generated by
 * `supabase gen types typescript` because no live Supabase project exists
 * in this environment yet. Once a project is linked, prefer regenerating
 * canonical row types with the Supabase CLI and keeping these as the
 * higher-level "domain" shapes services/repositories work with (which may
 * differ slightly from raw DB rows — e.g. camelCase, computed fields).
 *
 * Money fields are minor-unit integers — see backend/lib/money.
 * Timestamps are ISO-8601 UTC strings.
 */

import type { FulfillmentStatus, OrderStatus, PaymentStatus } from '../status'

export type ContentStatus = 'draft' | 'published' | 'archived'

export interface Brand {
  id: string
  name: string
  slug: string
  description: string | null
  logoUrl: string | null
  status: ContentStatus
}

export interface Category {
  id: string
  parentId: string | null
  name: string
  slug: string
  status: ContentStatus
}

export interface ProductVariant {
  id: string
  productId: string
  sku: string
  title: string | null
  price: number // minor units
  compareAtPrice: number | null // minor units
  currency: string
  attributes: Record<string, unknown>
  status: ContentStatus
  ledgixItemId: string | null
}

export interface Product {
  id: string
  brandId: string | null
  name: string
  slug: string
  shortDescription: string | null
  description: string | null
  status: ContentStatus
  isFeatured: boolean
  variants: ProductVariant[]
  images: ProductImage[]
}

export interface ProductImage {
  id: string
  productId: string
  variantId: string | null
  storagePath: string
  altText: string | null
  sortOrder: number
  isPrimary: boolean
}

export interface Customer {
  id: string
  profileId: string | null
  customerNumber: string
  firstName: string | null
  lastName: string | null
  email: string | null
  phone: string | null
  status: 'active' | 'inactive' | 'blocked'
  ledgixCustomerId: string | null
}

export interface CustomerAddress {
  id: string
  customerId: string
  label: string | null
  recipientName: string
  phone: string
  addressLine1: string
  addressLine2: string | null
  city: string
  province: string | null
  postalCode: string | null
  country: string
  isDefaultShipping: boolean
  isDefaultBilling: boolean
}

export interface OrderItem {
  id: string
  orderId: string
  productId: string | null
  variantId: string | null
  sku: string
  productName: string
  variantName: string | null
  quantity: number
  unitPrice: number // minor units, snapshotted
  originalPrice: number | null
  discountAmount: number
  lineTotal: number
}

export interface Order {
  id: string
  orderNumber: string
  customerId: string | null
  email: string | null
  phone: string | null
  currency: string
  subtotal: number
  discountTotal: number
  shippingTotal: number
  taxTotal: number
  grandTotal: number
  orderStatus: OrderStatus
  paymentStatus: PaymentStatus
  fulfillmentStatus: FulfillmentStatus
  paymentMethod: string | null
  source: 'web' | 'whatsapp' | 'mobile' | 'admin'
  ledgixInvoiceId: string | null
  ledgixInvoiceNumber: string | null
  items: OrderItem[]
  placedAt: string
}

export interface Payment {
  id: string
  orderId: string
  provider: 'easypaisa' | 'manual' | 'cod'
  providerTransactionId: string | null
  amount: number // minor units
  currency: string
  status: PaymentStatus
  paidAt: string | null
  refundedAmount: number
  ledgixReceiptId: string | null
}

export interface Shipment {
  id: string
  orderId: string
  provider: 'leopards' | 'manual'
  trackingNumber: string | null
  awbNumber: string | null
  status:
    | 'pending'
    | 'pickup_requested'
    | 'picked_up'
    | 'in_transit'
    | 'out_for_delivery'
    | 'delivered'
    | 'failed_delivery'
    | 'returned'
    | 'cancelled'
  shippingCost: number | null // minor units
  deliveredAt: string | null
}

export type ReturnStatus =
  | 'requested'
  | 'under_review'
  | 'approved'
  | 'rejected'
  | 'pickup_requested'
  | 'in_transit'
  | 'received'
  | 'refunded'
  | 'replaced'
  | 'closed'

export interface Return {
  id: string
  orderId: string
  customerId: string | null
  returnNumber: string
  status: ReturnStatus
  reason: string | null
  refundAmount: number | null // minor units
}

export type ErpSyncEntityType = 'customer' | 'product_variant' | 'order' | 'payment' | 'inventory'
export type ErpSyncStatus = 'pending' | 'in_progress' | 'succeeded' | 'failed' | 'skipped'

export interface ErpSyncEvent {
  id: string
  syncJobId: string
  entityType: ErpSyncEntityType
  status: ErpSyncStatus
  message: string | null
  createdAt: string
}
